# coding: utf-8
"""Interactive setup: ask a few questions, write the config files.

    bigqmt-init                              # console script
    python -m bigqmt_signal_trader.init_config   # same thing

Getting a working deployment previously meant copying two .example.py files,
knowing which of ~30 keys actually matter, and keeping the server and client
blocks consistent by hand. This asks for the handful that vary and derives the
rest.

Writes up to three things:

  * bigqmt_signal_trader_local_config.py   -- QMT-side (the python directory)
  * bigqmt_signal_trader_client_config.py  -- client-side
  * a single-file build with the config baked in, for sandboxes that allow
    neither external imports nor file loading (issue #56)

On passwords: the Redis password is a service credential and goes in the config
file, which is what the .example.py files already document. The QMT *login*
password is not stored -- qmt_launcher reads it from BIGQMT_LOGIN_PASSWORD so it
never reaches argv or a file on disk, and this tool keeps that arrangement.
"""

import getpass
import os
import subprocess
import sys


ACCOUNT_TYPES = ("STOCK", "CREDIT", "FUTURE", "STOCK_OPTION", "HUGANGTONG", "SHENGANGTONG")
TRANSPORTS = ("redis", "zmq")
DEPLOYMENTS = ("package", "single_file", "single_file_no_redis")

DEPLOYMENT_LABELS = {
    "package": "标准包部署（把 src/ 同步到 QMT 的 python 目录）",
    "single_file": "单文件（base64 内嵌，redis 或 zmq 均可）",
    "single_file_no_redis": "单文件（明文代码，强制 zmq；沙箱拒绝 import redis 时用）",
}

BUILDERS = {
    "single_file": ("build_single_file.py", "BIGQMT_REDIS_DRYRUN_ALL_IN_ONE.py", "utf-8"),
    "single_file_no_redis": (
        "build_no_redis_single_file_flat.py",
        "BIGQMT_DRYRUN_NO_REDIS_FLAT_ALL_IN_ONE.py",
        "gbk",
    ),
}

DEFAULTS = {
    "account_id": "",
    "account_type": "STOCK",
    "transport": "redis",
    "host": "127.0.0.1",
    "port": 6379,
    "db": 5,
    "username": "",
    "password": "",
    "allow_order_methods": False,
    "deployment": "package",
    "qmt_python_dir": "",
    "client_dir": "",
}


# ----------------------------------------------------------------------
# rendering
# ----------------------------------------------------------------------

def _zmq_default_port(account_id):
    """The zmq transport derives its port from the account id when no explicit
    address is configured; mirror that so the client block points somewhere
    real instead of a placeholder."""
    # Keep one source of truth for the derivation.  Duplicating the constants
    # here previously made bigqmt-init generate a client address in the 15000
    # range while the QMT-side ZmqTransport listened in the 15560 range.
    from .transports.zmq_transport import _default_zmq_port

    return _default_zmq_port(account_id)


def _zmq_server_bind_host(client_host):
    """Bind loopback for same-host clients, wildcard for a remote QMT host.

    ``client_host`` is the address the external program uses to reach the QMT
    machine.  A server cannot bind that public/DNS name reliably, so a remote
    deployment listens on all local interfaces and leaves interface/firewall
    restriction to the operator.
    """
    normalized = str(client_host or "").strip().lower()
    if normalized in ("", "127.0.0.1", "localhost"):
        from .transports.zmq_transport import DEFAULT_ZMQ_HOST

        return DEFAULT_ZMQ_HOST
    return "0.0.0.0"


def render_server_config(answers):
    """bigqmt_signal_trader_local_config.py -- read by the QMT-side strategy."""
    lines = [
        "# coding: utf-8",
        '"""Local private config for the QMT python directory.',
        "",
        "Generated by `bigqmt-init`.",
        "DO NOT COMMIT: this file holds an account id and Redis credentials.",
        '"""',
        "",
        "BIGQMT_ACCOUNT_ID = %r" % str(answers["account_id"]),
        "",
        "BIGQMT_ACCOUNT_TYPE = %r" % str(answers["account_type"]),
        "",
        "BIGQMT_REDIS_CONFIG = {",
        '    "transport": %r,' % str(answers["transport"]),
        '    "host": %r,' % str(answers["host"]),
        '    "port": %d,' % int(answers["port"]),
        '    "db": %d,' % int(answers["db"]),
        '    "username": %r,' % str(answers["username"]),
        '    "password": %r,' % str(answers["password"]),
    ]
    if str(answers["transport"]) == "zmq":
        port = _zmq_default_port(answers["account_id"])
        bind_host = _zmq_server_bind_host(answers["host"])
        lines.extend([
            "    # Same-host ZMQ stays on loopback. A remote QMT address makes the",
            "    # server bind all interfaces; restrict that port with a firewall.",
            '    "zmq": {"bind_address": "tcp://%s:%d"},' % (bind_host, port),
        ])
    if answers["allow_order_methods"]:
        lines.append("    # Remote order/cancel is ON. Turn it off if you only need queries.")
    else:
        lines.append("    # Remote order/cancel stays off until you explicitly want it.")
    lines.extend([
        '    "rpc_allow_order_methods": %r,' % bool(answers["allow_order_methods"]),
        "    # Requests drain through QMT's run_time(\"adjust\", ...) callback, on the",
        "    # main strategy thread. get_trade_detail_data returns EMPTY off that",
        "    # thread, so order/query methods must not move to a background thread.",
        '    "rpc_process_in_listener": True,',
        '    "rpc_listener_methods": ("*",),',
        '    "rpc_background_threads": False,',
        '    "schedule_adjust": True,',
        '    "schedule_adjust_interval": "100nMilliSecond",',
        '    "full_tick_cache_enabled": False,',
        '    "full_tick_demand_ttl_seconds": 10,',
        '    "full_tick_cache_ttl_seconds": 10,',
        '    "full_tick_refresh_interval_seconds": 0.5,',
        '    "full_tick_market_refresh_interval_seconds": 3,',
        '    "full_tick_refresh_max_wall_seconds": 0.3,',
        '    "full_tick_max_requests": 8,',
        '    "download_jobs_enabled": False,',
        '    "download_job_chunk_size": 10,',
        '    "download_job_max_wall_seconds": 0.5,',
        '    "download_job_ttl_seconds": 3600,',
        '    "exec_events_enabled": True,',
        '    "exec_events_debug_raw_fields": False,',
        "}",
        "",
    ])
    return "\n".join(lines)


def render_client_config(answers):
    """bigqmt_signal_trader_client_config.py -- read by the external program."""
    transport = str(answers["transport"])
    lines = [
        "# coding: utf-8",
        '"""Client-side private config.',
        "",
        "Generated by `bigqmt-init`.",
        "DO NOT COMMIT: this file holds an account id and Redis credentials.",
        '"""',
        "",
        "BIGQMT_ACCOUNT_ID = %r" % str(answers["account_id"]),
        "BIGQMT_RPC_TIMEOUT_SECONDS = 30.0",
        "",
        "BIGQMT_REDIS_CONFIG = {",
        '    "transport": %r,' % transport,
        '    "host": %r,' % str(answers["host"]),
        '    "port": %d,' % int(answers["port"]),
        '    "db": %d,' % int(answers["db"]),
        '    "username": %r,' % str(answers["username"]),
        '    "password": %r,' % str(answers["password"]),
    ]
    if transport == "zmq":
        port = _zmq_default_port(answers["account_id"])
        lines.extend([
            "    # QMT host/port are explicit so RPC and quote-push clients use the",
            "    # same machine. The server config generated alongside this file",
            "    # binds loopback for local use or 0.0.0.0 for a remote QMT host.",
            '    "zmq": {',
            '        "host": %r,' % str(answers["host"]),
            '        "port": %d,' % port,
            '        "connect_address": "tcp://%s:%d",' % (str(answers["host"]), port),
            "    },",
        ])
    lines.extend([
        "}",
        "",
        "# Reference/history reads go straight to Big QMT's FormulaServer (port",
        "# 58600) instead of over RPC. Every miss falls back to RPC, so an",
        "# unreachable 58600 changes nothing.",
        "BIGQMT_FORMULA_SERVER_CONFIG = {",
        '    "enabled": True,',
        "}",
        "",
        "BIGQMT_LOCAL_CACHE_CONFIG = {",
        '    "enabled": True,',
        '    "dir": None,',
        '    "fallback_rpc": True,  # MiniQMT-compatible adjusted reads; False = offline only',
        '    "format": "auto",',
        "}",
        "",
    ])
    return "\n".join(lines)


def render_single_file_config_block(answers):
    """The config block the single-file builds carry at the top of the file.

    This block IS the config for a single-file deployment: the build never
    reads bigqmt_signal_trader_local_config.py from disk -- it synthesises that
    module from the block embedded here. So anything render_server_config emits
    and this does not is simply lost, silently, and editing local_config.py on
    the QMT machine changes nothing (issue #153).

    Two keys used to be missing:

      * ``zmq`` -- so the transport fell back to DEFAULT_ZMQ_HOST and bound
        tcp://127.0.0.1 no matter what address was answered. The reporter saw
        `zmq started bound=tcp://127.0.0.1:15618` while their local_config said
        0.0.0.0, and had to patch DEFAULT_ZMQ_HOST in the generated file.
      * ``transport`` -- the no-redis FLAT build forces zmq afterwards so it
        got away with it, but the base64 single_file build does not: answering
        transport=zmq there produced a server that ran redis while the client
        spoke zmq, which is exactly the "客户端 transport 和服务端不匹配"
        timeout the ping check reports.
    """
    transport = str(answers["transport"])
    lines = [
        "BIGQMT_ACCOUNT_ID = %r" % str(answers["account_id"]),
        "",
        "BIGQMT_ACCOUNT_TYPE = %r" % str(answers["account_type"]),
        "",
        "BIGQMT_REDIS_CONFIG = {",
        '    "transport": %r,' % transport,
        '    "host": %r,' % str(answers["host"]),
        '    "port": %d,' % int(answers["port"]),
        '    "db": %d,' % int(answers["db"]),
        '    "username": %r,' % str(answers["username"]),
        '    "password": %r,' % str(answers["password"]),
    ]
    if transport == "zmq":
        port = _zmq_default_port(answers["account_id"])
        bind_host = _zmq_server_bind_host(answers["host"])
        lines.extend([
            "    # Same-host ZMQ stays on loopback. A remote QMT address makes the",
            "    # server bind all interfaces; restrict that port with a firewall.",
            "    # A single-file build has no local_config.py to read, so this",
            "    # block is the only place the bind address can come from (#153).",
            '    "zmq": {"bind_address": "tcp://%s:%d"},' % (bind_host, port),
        ])
    lines.extend([
        '    "rpc_allow_order_methods": %r,' % bool(answers["allow_order_methods"]),
        '    "rpc_process_in_listener": True,',
        '    "rpc_listener_methods": ("*",),',
        '    "rpc_background_threads": False,',
        '    "schedule_adjust": True,',
        '    "schedule_adjust_interval": "100nMilliSecond",',
        '    "full_tick_cache_enabled": False,',
        '    "full_tick_demand_ttl_seconds": 10,',
        '    "full_tick_cache_ttl_seconds": 10,',
        '    "full_tick_refresh_interval_seconds": 0.5,',
        '    "full_tick_market_refresh_interval_seconds": 3,',
        '    "full_tick_refresh_max_wall_seconds": 0.3,',
        '    "full_tick_max_requests": 8,',
        '    "download_jobs_enabled": False,',
        '    "download_job_chunk_size": 10,',
        '    "download_job_max_wall_seconds": 0.5,',
        '    "download_job_ttl_seconds": 3600,',
        '    "exec_events_enabled": True,',
        '    "exec_events_debug_raw_fields": False,',
        "}",
    ])
    return "\n".join(lines)


def inject_single_file_config(source, answers):
    """Replace a generated build's placeholder config block with real answers.

    Raises ValueError rather than returning the source unchanged: silently
    shipping a file that still says YOUR_ACCOUNT_ID would look like success.
    """
    start = source.find("BIGQMT_ACCOUNT_ID = ")
    if start < 0:
        raise ValueError("no config block found in the generated build")
    marker = "\n}\n"
    end = source.find(marker, start)
    if end < 0:
        raise ValueError("config block is not terminated in the generated build")
    return source[:start] + render_single_file_config_block(answers) + source[end + len(marker) - 1:]


# ----------------------------------------------------------------------
# prompting
# ----------------------------------------------------------------------

def _ask(write, read, question, default="", choices=None, secret=False,
         read_secret=None):
    while True:
        if choices:
            write("\n%s\n" % question)
            for index, choice in enumerate(choices, 1):
                label = DEPLOYMENT_LABELS.get(choice, choice)
                marker = " (默认)" if choice == default else ""
                write("  %d) %s%s\n" % (index, label, marker))
            raw = read("请选择 [1-%d]: " % len(choices)).strip()
            if not raw:
                return default
            if raw.isdigit() and 1 <= int(raw) <= len(choices):
                return choices[int(raw) - 1]
            if raw in choices:
                return raw
            write("  无效选择，请重试。\n")
            continue

        suffix = " [%s]" % default if default != "" else ""
        if secret:
            ask_secret = read_secret or getpass.getpass
            raw = ask_secret("%s%s: " % (question, suffix))
        else:
            raw = read("%s%s: " % (question, suffix))
        raw = raw.strip()
        return raw if raw else default


def _ask_bool(read, question, default=False):
    hint = "Y/n" if default else "y/N"
    raw = read("%s [%s]: " % (question, hint)).strip().lower()
    if not raw:
        return default
    return raw in ("y", "yes", "是", "1", "true")


def _ask_int(write, read, question, default):
    while True:
        raw = _ask(write, read, question, str(default))
        try:
            return int(raw)
        except ValueError:
            write("  需要一个整数。\n")


def prompt_answers(write, read, read_secret=None):
    answers = dict(DEFAULTS)

    write("\n=== Big QMT 桥接配置 ===\n")

    while not answers["account_id"]:
        answers["account_id"] = _ask(write, read, "资金账号")
        if not answers["account_id"]:
            write("  账号不能为空。\n")

    answers["account_type"] = _ask(
        write, read, "账号类型", default="STOCK", choices=ACCOUNT_TYPES)

    answers["transport"] = _ask(
        write, read, "传输方式", default="redis", choices=TRANSPORTS)

    if answers["transport"] == "redis":
        answers["host"] = _ask(write, read, "Redis 地址", DEFAULTS["host"])
        answers["port"] = _ask_int(write, read, "Redis 端口", DEFAULTS["port"])
        answers["db"] = _ask_int(write, read, "Redis db", DEFAULTS["db"])
        answers["username"] = _ask(write, read, "Redis 用户名（无则回车）", "")
        answers["password"] = _ask(
            write, read, "Redis 密码（无则回车，输入不回显）", "",
            secret=True, read_secret=read_secret)
    else:
        answers["host"] = _ask(
            write, read,
            "QMT 终端地址（同机用 127.0.0.1；跨机填 QMT 主机 IP/主机名）",
            DEFAULTS["host"],
        )
        answers["port"] = _zmq_default_port(answers["account_id"])
        write("  zmq 端口按账号推导为 %d（服务端日志会打印实际绑定端口）。\n"
              % answers["port"])
        if _zmq_server_bind_host(answers["host"]) == "0.0.0.0":
            write(
                "  跨机 ZMQ 会让 QMT 服务端绑定 0.0.0.0；请用 Windows "
                "防火墙把该端口限制到可信客户端。\n"
            )

    write("\n远程下单/撤单默认关闭。打开后，任何能连上这条通道的程序都可以下单。\n")
    answers["allow_order_methods"] = _ask_bool(
        read, "允许远程下单/撤单？", default=False)

    answers["deployment"] = _ask(
        write, read, "部署方式", default="package", choices=DEPLOYMENTS)

    if answers["deployment"] == "single_file_no_redis":
        answers["transport"] = "zmq"
        write("  单文件无 redis 版强制使用 zmq 传输。\n")

    answers["qmt_python_dir"] = _ask(
        write, read, "QMT 的 python 目录（回车则写到当前目录）", "")
    answers["client_dir"] = _ask(
        write, read, "客户端配置写到哪个目录（回车则当前目录）", "")
    return answers


# ----------------------------------------------------------------------
# writing
# ----------------------------------------------------------------------

def _confirm_overwrite(write, read, path, force):
    if not os.path.exists(path) or force:
        return True
    return _ask_bool(read, "%s 已存在，覆盖？" % path, default=False)


def _write(path, text, encoding="utf-8"):
    parent = os.path.dirname(os.path.abspath(path))
    if parent and not os.path.isdir(parent):
        os.makedirs(parent)
    with open(path, "w", encoding=encoding, newline="\n") as handle:
        handle.write(text)
    # Best effort: the file holds credentials, so keep it owner-readable where
    # the platform supports it. Windows ignores this; NTFS ACLs are separate.
    try:
        os.chmod(path, 0o600)
    except OSError:
        pass


def build_single_file(repo_root, deployment, answers, out_path=None):
    """Run the matching builder and bake the answers into its config block."""
    script, default_name, encoding = BUILDERS[deployment]
    builder = os.path.join(repo_root, "tools", script)
    if not os.path.exists(builder):
        raise ValueError(
            "builder not found: %s (run this from a source checkout)" % builder)
    target = out_path or os.path.join(os.getcwd(), default_name)
    env = dict(os.environ, BIGQMT_BUILD_OUT=target)
    completed = subprocess.run(
        [sys.executable, builder], env=env,
        stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    if completed.returncode != 0:
        raise ValueError("%s failed:\n%s"
                         % (script, completed.stdout.decode("utf-8", "replace")))
    with open(target, encoding=encoding) as handle:
        source = handle.read()
    with open(target, "w", encoding=encoding, newline="\n") as handle:
        handle.write(inject_single_file_config(source, answers))
    return target


def apply(answers, repo_root, write, read, force=False):
    """Write everything the answers call for. Returns the paths written."""
    written = []

    server_dir = answers["qmt_python_dir"] or os.getcwd()
    server_path = os.path.join(server_dir, "bigqmt_signal_trader_local_config.py")
    if _confirm_overwrite(write, read, server_path, force):
        _write(server_path, render_server_config(answers))
        written.append(server_path)

    client_dir = answers["client_dir"] or os.getcwd()
    client_path = os.path.join(client_dir, "bigqmt_signal_trader_client_config.py")
    if _confirm_overwrite(write, read, client_path, force):
        _write(client_path, render_client_config(answers))
        written.append(client_path)

    if answers["deployment"] in BUILDERS:
        _script, default_name, _encoding = BUILDERS[answers["deployment"]]
        target = os.path.join(server_dir, default_name)
        if _confirm_overwrite(write, read, target, force):
            written.append(build_single_file(
                repo_root, answers["deployment"], answers, out_path=target))

    return written


def _report(write, answers, written):
    write("\n=== 已写入 ===\n")
    for path in written:
        write("  %s\n" % path)
    if not written:
        write("  （没有文件被写入）\n")
        return

    write("\n这些文件包含账号和凭据，不要提交到版本库。\n")

    if answers["deployment"] == "package":
        write("\n下一步：把 src/ 下的包同步到 QMT 的 python 目录，"
              "在策略编辑器里加载 BIGQMT_REDIS_DRYRUN.py。\n")
    else:
        write("\n下一步：把生成的单文件拷进 QMT 的 python 目录并作为策略加载，"
              "不需要一并拷贝整个包。\n")

    if answers["allow_order_methods"]:
        write("\n注意：远程下单/撤单已打开。任何能连上这条通道的程序都可以下单。\n")

    write("\nqmt_launcher 的自动登录密码不写进配置文件——"
          "它从环境变量 BIGQMT_LOGIN_PASSWORD 读取，\n"
          "这样密码不会出现在 argv 或磁盘文件里。需要时先设置该环境变量。\n")


def main(argv=None):
    import argparse

    parser = argparse.ArgumentParser(
        prog="bigqmt-init",
        description="交互式生成 Big QMT 桥接的服务端/客户端配置。")
    parser.add_argument("--force", action="store_true",
                        help="已存在的文件直接覆盖，不再询问")
    parser.add_argument("--repo-root", default=None,
                        help="仓库根目录（单文件构建需要 tools/ 下的生成器）")
    args = parser.parse_args(argv)

    repo_root = args.repo_root or os.path.dirname(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

    write = sys.stdout.write
    read = lambda prompt: input(prompt)  # noqa: E731 -- injected in tests

    try:
        answers = prompt_answers(write, read)
        written = apply(answers, repo_root, write, read, force=args.force)
    except KeyboardInterrupt:
        write("\n已取消，未写入任何文件。\n")
        return 1
    except ValueError as exc:
        write("\n失败：%s\n" % exc)
        return 1

    _report(write, answers, written)
    return 0


if __name__ == "__main__":
    sys.exit(main())
